spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
#      routes:
#        # Routes for course Service
#        - id: course-service
#          uri: lb://course-service
#          predicates:
#            - Path=/api/course-service/**
#        # Routes for user Service
#        - id: user-service
#          uri: lb://user-service
#          predicates:
#            - Path=/api/user-service/**
server:
  port: 9999

eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: DEBUG

jwt:
  secret: MySuperSecretKey1234567890123456
